name: Update README

on:
  schedule:
   # https://crontab.guru/
   # 0 1 * * * 매일 새벽 1시에 실행
   # 0 0 * * 0 매주 일요일 00:00에 실행
   # 0 */1 * * * 매일 1시간마다 실행
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
