name: Update README

on:
  schedule:
   # 실제 스케쥴 작업이 시작될 cron을 등록하면 됩니다.
   # 크론은 https://crontab.guru/ 여기서 확인하면 좋을 것 같습니다.
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}